/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardPolicyPanel: typeof import('./components/CardPolicyPanel.vue')['default']
    CarrierWebsheetDialog: typeof import('./components/CarrierWebsheetDialog.vue')['default']
    DebugPanel: typeof import('./components/DebugPanel.vue')['default']
    DeviceAddDialog: typeof import('./components/DeviceAddDialog.vue')['default']
    DeviceAtTab: typeof import('./components/DeviceAtTab.vue')['default']
    DeviceCard: typeof import('./components/DeviceCard.vue')['default']
    DeviceConfigTab: typeof import('./components/DeviceConfigTab.vue')['default']
    DeviceDetailHeader: typeof import('./components/DeviceDetailHeader.vue')['default']
    DeviceDetailLoading: typeof import('./components/DeviceDetailLoading.vue')['default']
    DeviceEsimTab: typeof import('./components/DeviceEsimTab.vue')['default']
    DeviceListPanel: typeof import('./components/DeviceListPanel.vue')['default']
    DeviceOverviewTab: typeof import('./components/DeviceOverviewTab.vue')['default']
    DeviceUssdTab: typeof import('./components/DeviceUssdTab.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    EsimCardPolicyInline: typeof import('./components/EsimCardPolicyInline.vue')['default']
    FieldRow: typeof import('./components/FieldRow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IncomingCallModal: typeof import('./components/IncomingCallModal.vue')['default']
    ListSkeleton: typeof import('./components/ListSkeleton.vue')['default']
    LoadingScreen: typeof import('./components/LoadingScreen.vue')['default']
    OperatorSelectionDialog: typeof import('./components/OperatorSelectionDialog.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    ProxyManagementTab: typeof import('./components/ProxyManagementTab.vue')['default']
    RefreshButton: typeof import('./components/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLight: typeof import('./components/StatusLight.vue')['default']
    SwitchDark: typeof import('./components/SwitchDark.vue')['default']
    TrafficAnalysisPanel: typeof import('./components/TrafficAnalysisPanel.vue')['default']
    UserGuideDialog: typeof import('./components/UserGuideDialog.vue')['default']
  }
}
